name: Playwright Tests

on:
  push:
    branches:
      - dev

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1  # or ${{ secrets.AWS_REGION }}

    - name: Install dependencies in shared
      working-directory: ./shared
      run: npm ci

    - name: Install backend dependencies
      working-directory: ./backend
      run: npm ci
    
    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm ci

    - name: Install Playwright Test and Browsers
      working-directory: ./frontend
      run: npx playwright install --with-deps
    
    - name: Install wait-on
      run: npm install -g wait-on

    - name: Install start-server-and-test
      run: npm install -g start-server-and-test

    - name: Start backend + frontend and run Playwright
      run: |
        npm start --prefix backend > backend.log 2>&1 &
        backend_pid=$!
        echo "Backend started (PID $backend_pid)"

        npx wait-on http://localhost:5000/health
        echo "Backend ready!"

        npm start --prefix frontend > frontend.log 2>&1 &
        frontend_pid=$!
        echo "Frontend started (PID $frontend_pid)"

        npx wait-on http://localhost:4200
        echo "Frontend ready!"
        
        cd frontend
        npx playwright test

        kill $backend_pid
        kill $frontend_pid
      env:
        NODE_ENV: test
        PORT: 5000
        REDIS_URL: redis://localhost:6379
        API_URL: http://localhost:5000
        FRONTEND_URL: http://localhost:4200
        MONGO_STRING: ${{ secrets.BACKEND_MONGO_STRING }}
        AUTH0_DOMAIN: ${{ secrets.BACKEND_AUTH0_DOMAIN }}
        AUTH0_CLIENT: ${{ secrets.BACKEND_AUTH0_CLIENT }}
        AUTH0_SECRET: ${{ secrets.BACKEND_AUTH0_SECRET }}
        AUTH0_AUDIENCE: ${{ secrets.BACKEND_AUTH0_AUDIENCE }}
        AUTH0_API_AUD: ${{ secrets.FRONTEND_AUTH0_API_AUD }}
        TEST_EMAIL: ${{ secrets.TEST_EMAIL }}
        TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: frontend/playwright-report/
        retention-days: 30
